rails-app/config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  get '/o-autorovi', to: 'static_pages#author', as: 'author'
  get '/o-pruvodci', to: 'static_pages#about', as: 'about'
  resources :camps, only: [:index, :show, :search], path: '/tabory', as: 'camps'
  root :to => "camps#index"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
end

rails-app/app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

rails-app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

rails-app/app/models/camp.rb
class Camp < ApplicationRecord
  searchkick

  def search_data
    {
      name: name
    }
  end
end

rails-app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

rails-app/app/controllers/camps_controller.rb
class CampsController < ApplicationController
  before_action :set_camp, only: [:show, :edit, :update, :destroy]

  # GET /camps
  # GET /camps.json
  def index
    if params[:q].present?
      @camps = Camp.search(params[:q], page: params[:page], fields: ["name^10"], misspellings: {edit_distance: 2})
    else
      @camps, @alphaParams = Camp.all.alpha_paginate(params[:letter], {:js => false, :include_all => false, :default_field => "A", :pagination_class => "d-flex flex-wrap", :bootstrap4 => true}){|camp| camp.name}
    end

    @geojson = Array.new

    @geocamps = Camp.all
    @geocamps.each do |camp|
      if camp.lat && camp.lng
        @geojson << {
          type: 'Feature',
          geometry: {
            type: 'Point',
            coordinates: [camp.lng, camp.lat]
          },
          properties: {
            id: camp.id,
            name: camp.name,
            :'marker-color' => '#00607d',
            :'marker-symbol' => 'circle',
            :'marker-size' => 'medium'
          }
        }
      end
    end

    respond_to do |format|
      format.html
      format.json { render json: @geojson }  # respond with the created JSON object
    end

  end


  # GET /camps/1
  # GET /camps/1.json
  def show
  end

  # GET /camps/new
  def new
    @camp = Camp.new
  end

  # GET /camps/1/edit
  def edit
  end

  # POST /camps
  # POST /camps.json
  def create
    @camp = Camp.new(camp_params)

    respond_to do |format|
      if @camp.save
        format.html { redirect_to @camp, notice: 'Camp was successfully created.' }
        format.json { render :show, status: :created, location: @camp }
      else
        format.html { render :new }
        format.json { render json: @camp.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /camps/1
  # PATCH/PUT /camps/1.json
  def update
    respond_to do |format|
      if @camp.update(camp_params)
        format.html { redirect_to @camp, notice: 'Camp was successfully updated.' }
        format.json { render :show, status: :ok, location: @camp }
      else
        format.html { render :edit }
        format.json { render json: @camp.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /camps/1
  # DELETE /camps/1.json
  def destroy
    @camp.destroy
    respond_to do |format|
      format.html { redirect_to camps_url, notice: 'Camp was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_camp
      @camp = Camp.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def camp_params
      params.require(:camp).permit(:name, :content, :lat, :lng)
    end
end

rails-app/app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def about
  end

  def author
  end

  def reference
  end
end

rails-app/app/helpers/application_helper.rb
module ApplicationHelper
  def markdown(text)
    options = {
      filter_html:     true,
      hard_wrap:       true,
      # link_attributes: { rel: 'nofollow', target: "_blank" },
      link_attributes: { rel: 'nofollow' },
      space_after_headers: true,
      fenced_code_blocks: true
    }

    extensions = {
      autolink:           true,
      superscript:        true,
      footnotes:          true, 
      disable_indented_code_blocks: true
    }

    renderer = Redcarpet::Render::HTML.new(options)
    markdown = Redcarpet::Markdown.new(renderer, extensions)

    markdown.render(text).html_safe
  end
  def camps_links(code)
    code = code.gsub('\<strong>(.*?)\<\/strong\>','$1')
  end
end

rails-app/app/helpers/camps_helper.rb
module CampsHelper
end

rails-app/app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

rails-app/app/views/camps/_form.html.erb
<%= form_with(model: camp, local: true) do |form| %>
  <% if camp.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(camp.errors.count, "error") %> prohibited this camp from being saved:</h2>

      <ul>
      <% camp.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :camp_name %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content, id: :camp_content %>
  </div>

  <div class="field">
    <%= form.label :lat %>
    <%= form.text_field :lat, id: :camp_lat %>
  </div>

  <div class="field">
    <%= form.label :lng %>
    <%= form.text_field :lng, id: :camp_lng %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

rails-app/app/views/camps/edit.html.erb
<h1>Editing Camp</h1>

<%= render 'form', camp: @camp %>

<%= link_to 'Show', @camp %> |
<%= link_to 'Back', camps_path %>

rails-app/app/views/camps/index.html.slim
p#notice= notice

- if params[:q].blank?
  nav = alphabetical_paginate @alphaParams
- else
  p Výsledky vyhledávání:

ul#pagination_table
  - @camps.each do |camp|
    li 
      = link_to camp.name, camp
      - if camp.lat && camp.lng
        span
          i.fa.fa-map-o data-toggle="tooltip" data-placement="right" title="Lokalizováno v mapě"

rails-app/app/views/camps/new.html.erb
<h1>New Camp</h1>

<%= render 'form', camp: @camp %>

<%= link_to 'Back', camps_path %>

rails-app/app/views/camps/show.html.slim
p#notice= notice
h1 = @camp.name
.camp-content data-id=@camp.id name=@camp.name
  = markdown(@camp.content)
/ span = link_to 'Zpět', camps_path

rails-app/app/views/layouts/_footer.html.slim
footer.footer.bg-dark
  .container.text-light
    .d-md-flex.justify-content-between.align-items-center.py-3
      p
        | Tato stránka vznikla v rámci projektu
        a href="https://cechoslovacivgulagu.cz/" target="_blank"  Čechoslováci v Gulagu
        br/
        | &copy; #{Date.today.year} Ústav pro studium totalitních režimů
      a href="https://www.ustrcr.cz/" target="_blank" 
        img.pt-md-0 height="52px" src="#{asset_path('logo-ustr.svg')}" alt="Logo Ústav pro studium totalitních režimů" /

rails-app/app/views/layouts/_header.html.slim
nav.navbar.navbar-expand-lg.navbar-dark.bg-dark.fixed-top
  .container
    = link_to "Průvodce říší zla", root_path, :class => "navbar-brand"
    button.navbar-toggler aria-controls="navbarContent" aria-expanded="false" aria-label=("Toggle navigation") data-target="#navbarContent" data-toggle="collapse" type="button" 
      span.navbar-toggler-icon
    #navbarContent.collapse.navbar-collapse
      ul.navbar-nav.mr-auto.mt-2.mt-lg-0
        = link_to "O průvodci", about_path, :class => "nav-item nav-link"
        = link_to "O autorovi", author_path, :class => "nav-item nav-link"
      = form_tag camps_path, class: "form-inline", method: :get do
        = text_field_tag :q, params[:q], class: "form-control mr-sm-2"
        = submit_tag "Vyhledat", class: "btn btn-primary my-2 my-sm-0"

rails-app/app/views/layouts/application.html.slim
doctype html
html lang="cs"
  head
    meta content="IE=edge,chrome=1" http-equiv="X-UA-Compatible"
    meta charset="utf-8"
    meta content="width=device-width,initial-scale=1.0,minimum-scale=1.0,maximum-scale=1.0,user-scalable=no,shrink-to-fit=no" name="viewport"
    title Průvodce říší zla - Vladimír Bystrov
    meta(
      property="description"
      content="Náš průvodce obsahuje údaje o více než 2100 koncentračních, nápravněpracovních, zvláštních, výrobních, zajateckých, internačních, prověřovacích filtračních táborech a zvláštních osadách zřízených od dvacátých do šedesátých let dvacátého století v Sovětském svazu a táborech, které Sovětský svaz zřídil v letech 1939-1950 v jiných zemích.")
    = csrf_meta_tags
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' 
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    

  body
    = render 'layouts/header'
    
    .map-content
      #map.map-open
      span#toogler
        i.fa.fa-angle-up.normal
    .main-content
      .container
        = yield
    span#back-to-top.btn.btn-primary.btn-lg.back-to-top data-placement="left" data-toggle="tooltip" href="#" role="button" title=("Zpět nahoru")
      i.fa.fa-arrow-up
    
    = render 'layouts/footer'

rails-app/app/views/static_pages/about.html.slim
markdown:
  # Co najdete a co nenajdete v průvodci

  *(z úvodu Vladimíra Bystrova ke knižnímu vydání Průvodce říší zla v roce 2006)*

  Náš průvodce obsahuje údaje o více než 2100 koncentračních, nápravněpracovních, zvláštních, výrobních, zajateckých, internačních, prověřovacích filtračních táborech a zvláštních osadách zřízených od dvacátých do šedesátých let dvacátého století v Sovětském svazu a táborech, které Sovětský svaz zřídil v letech 1939-1950 v jiných zemích.

  Především jsem se snažil kromě 476 ústředně řízených táborových centrál, které jsou popsány ruskými historiky podle dokumentů v centrálních archivech, zaznamenat co nejvíce jednotlivých součástí těchto komplexů, táborových oddělení, samostatných táborových oddělení, táborových středisek, samostatných táborových středisek, detašovaných a různých dalších táborů, pokud se o nich dochovala alespoň nějaká svědectví anebo dokonce měly své vlastní jméno, dané jim místními obyvateli nebo samotnými vězni.

  Uvědomuji si totiž, že soustřeďováním pozornosti jen na faktografický popis centrál, jak je často obvyklé, se náš pohled nebezpečně zužuje a vytrácí se reálná představa o někdy až stovkách jednotlivých táborů různé kapacity, roztroušených na území velikostí nezřídka odpovídajícím nejednomu evropského státu, které tvořily mikrokosmos každé takové centrály. A právě proto jsem do průvodce zařadil zmínky alespoň o některých z nich, tak jak jsou zaznamenány v dosud zveřejněných dokumentech, ale především v memoárové literatuře nebo jak byly získány výzkumem založeném na metodě orální historie. Přičemž jsem si vědom toho, že jsem mohl postihnout pouze nepatrnou část a že historické bádání a zpracovávání vzpomínek bývalých vězňů nebo jiných pamětníků doslova každý den přináší další informace o dosud nepřipomínaných nebo zapomenutých větších či menších, stálých či dočasných táborech. Nebo o dosud neznámých proměnách táborových konglomerátů v čase či dalších jménech nebo označeních, daných jednotlivým táborům jejich současníky. Podle obecného odhadu bylo v 476 ústředně řízených táborových centrálách za celé období od konce dvacátých do šedesátých let soustředěno kolem dvaceti a možná ještě více tisíc táborů a v průvodci jsem mohl připomenout pouze zlomek z nich.

  Údaje a informace o těchto jednotlivých táborech, zřizovaných, opouštěných, rušených, obnovovaných nebo přenechávaných na čas nebo natrvalo jiným centrálám se však dochovaly velmi nerovnoměrně a spíš v místních než ústředních archivech. A ne vždy souhlasí tyto oficiální údaje s tím, na co vzpomínají bývalí vězni nebo jiní pamětníci, přičemž vzpomínky často zaznamenané až se značným časovým odstupem od krutého zážitku rovněž nejsou příliš koherentní. Proto je třeba smířit se s tím, že dobrat se přes předěl let historické pravdy je někdy stále obtížnější a udělat si úplný přehled o konglomerátu táborů v každé centrále po celou dobu její existence je zřejmě již navždy vyloučeno.

  Průvodce dále obsahuje informace o více než dvou stech táborech pro válečné zajatce a internované, které byly zřízeny v Sovětském svazu po druhé světové válce a podle mého názoru jsou nesprávně opomíjeny, když se připomíná svět sovětských táborů. Tyto tábory byly totiž doslova pupeční šňůrou spojeny s ostatní táborovou strukturou.

  Především byly také řízeny Lidovým komisariátem vnitra SSSR a později Ministerstvem vnitra SSSR a pouze podléhaly jiné hlavní správě. Zajatci v rozporu s mezinárodními úmluvami, k nimž se však Sovětský svaz nepřipojil, byli rovněž masově využíváni jako pracovní síla v sovětském národním hospodářství, obdobně jako vězni v nápravněpracovních táborech, podléhali sovětské jurisdikci a trestáni podle sovětského trestního zákoníku. Proto byly tábory Hlavní správy pro záležitosti válečných zajatců a internovaných nejednou umisťovány v sousedství nebo dokonce v prostorách ostatních táborů a měly společná pracoviště. Ale zejména nelze přehlédnout, kdo tvořil masu označovanou jako internovaní: že to bylo civilní obyvatelstvo odvlečené na práci do Sovětského svazu z území obsazených Rudou armádou během jejího postupu v průběhu války. Od Sovětským svazem anektovaného původně východního Polska a násilně připojených pobaltských zemí a Besarábie, až po starce a ženy z Německa a desítky tisíc mužů a žen z Maďarska, Rumunska a Slovenska. Ještě koncem čtyřicátých let byly do těchto táborů přiváženy transporty hlavně žen z Německa a Pobaltí.

  Postavení internovaných se lišilo od postavení vězňů nápravněpracovních táborů pouze tím, že nebyli odsouzeni. A teprve, když počátkem padesátých let byla většina válečných zajatců propuštěna, byli všichni internovaní administrativním rozsudkem odsouzeni a spolu se zbytkem zajatců převedeni nejprve do táborů Správy pro záležitosti odsouzených válečných zajatců a internovaných a odtud postupně do běžných nápravněpracovních táborů nebo posláni do vyhnanství v hloubi země.

  Ruští historici a veřejnost věnují těmto táborům zatím jen okrajovou pozornost. Bolestné rozkrývání rozsahu a hloubky perzekuce vlastního obyvatelstva bohužel zastiňuje represe spáchané Sovětským svazem také  na občanech jiných zemí. Navíc adorace úspěchu Sovětského svazu ve druhé světové válce zřejmě brání příliš otevírat téma zločinného chování vítěze. Ale především je přezíravost k osudům příslušníků jiných národů v sovětských táborech způsobována přetrvávajícím velmocenským šovinismem Ruska. Ten totiž stále neumožňuje této zemi pochopit, jaké tragédie způsobila Evropě a světu dvacátého století.

  To byl také důvod, proč je v našem průvodci dále zařazeno několik desítek táborů, v nichž Lidový komisariát vnitra SSSR po násilném rozdělení Polska mezi Německo a Sovětský svaz v září 1939 internoval příslušníky polské armády a funkcionáře státní správy a různých úřadů, zadržené na dosavadních polských východních územích, a nejpozději v první polovině roku 1941 je deportoval do nápravněpracovních táborů v hloubi Sovětské svazu. Některé polské jednotky sice kladly Rudé armádě odpor často označovaný jako polsko-sovětská válka, ale žádná ze stran nevyhlásila válečný stav a sovětská okupace východních území Polska byla tehdy jednostranným aktem agrese Sovětského svazu proti Polsku.

  Tragedie polských důstojníků a dalších Poláků popravených v březnu a dubnu 1940 v Katyňském lese nedaleko Smolenska a desítky tisíc obyvatel Polska vězněných v sovětských nápravněpracovních táborech až do šedesátých let pochopitelně rovněž bohužel nejsou příliš frekventovaným tématem v pracích současných ruských historiků zabývajících se světem sovětských táborů. Česká veřejnost by však bezprecendentní zločin Sovětského svazu spáchaný na Polsku a jeho obyvatelích podle mého názoru měla znát.

  V průvodci je věnována pozornost také dalším u nás málo známým sovětským táborům. Například zvláštním táborům a prověřovacím a filtračním táborům, v nichž v závěru druhé světové války byli jako nespolehliví soustřeďováni bývalí příslušníci Rudé armády, vracející se z německého zajetí, a sovětští občané, kteří byli v prvních letech druhé světové války v době okupace západních území Sovětského svazu německou armádou odvlečeni na práci do Německa. Především však táborům zřízeným Sovětským svazem ve druhé polovině čtyřicátých let v Německu a dalších zemích střední a východní Evropy nevyjímaje ani Československo.

  Okrajově jsou v průvodci připomenuty také některé zvláštní osady, do nichž byli v různých permanentních kampaních umisťovány milióny sovětských občanů násilně přemisťovaných ze svých původních domovů do vzdálených, zpravidla dosud neosídlených míst. Desetitisíce osad byly integrální součástí jednotlivých táborových centrál a život jejich obyvatel se zpravidla příliš nelišil od režimu v táborech. Není však již v silách žádného historika shromáždit údaje o všech osadách pro přesídlence a vysídlence nejrůznějšího druhu během dvacátých až padesátých let. V našem průvodci jsou proto zmíněny jen osady bohužel proslulé svým tragickým osudem.

  Až na nepatrné výjimky nejsou v našem průvodci uvedeny také koncentrační tábory a kolonie z prvních let po převzetí moci v Rusku bolševiky a ani věznice a kolonie nebo tábory zřizované regionálními orgány bezpečnosti v jednotlivých republikách nebo oblastech Sovětského svazu. Ústřední evidence neexistovala a teprve dnes se alespoň některé oblasti země snaží rekonstruovat vývoj a hustotu sítě táborů a věznic často označovaných různými novotvary z postrevolučního slovníku. Obecně to však byla vesměs obvyklá vězeňská nebo koncentrační zařízení ještě bez nucené práce vězňů a proto jsme jim věnovali pouze minimální pozornost.

  Bylo by bláhové chtít zaznamenat v jednom díle celý obraz říše zla vybudované v Sovětském svazu ve dvacátém století a patrně to ani nebude nikdy možné. I to málo, co je soustředěno v průvodci, který právě držíte v ruce, podle mého názoru vydává však dostatečně přesvědčivé svědectví o brutálním světě vytvořeném komunistickým snílky v obrovské zemi na východě.

  # Jak číst v průvodci

  Protože jsem přesvědčen, že ruština je dnes již pro několik českých generací jako kterýkoliv jiný cizí jazyk a ani její předcházející čtyřicetiletou výuku nepřeceňuji, jsou u všech názvů institucí, zeměpisných jmen a dalších specifických pojmů uvedena v závorce originální ruské znění v přepisu latinkou. Jsem si totiž vědom až příliš časté nekompability jevů z ruské sovětské skutečnosti v různých historických obdobích s historickými nebo současnými českými zkušenostmi a tím pádem také nesnadnosti přesně jednotlivé pojmy přeložit do češtiny. Proto ponechávám na čtenáři možnost opravit mne – ať již jde o názvy organizací, českou transkripci ruských i neruských místních jmen nebo o specifické pracovní a výrobní činnosti.

  Protože jsem přesvědčen, že náš průvodce není četbou, která se může číst postupně od stránky ke stránce, je každé heslo důsledně samostatné. V každém je uveden vždy úplný název tábora nebo jeho označení, komu podléhal a kde se nalézal, samozřejmě vždy s uvedením originálního ruského znění názvů institucí a místních pojmenování, od kdy do kdy existoval a všechny další dosažitelné informace. Každé heslo je rovněž opatřeno vlastními vysvětlivkami a kromě nepříliš četných výjimek neobsahuje odkazy, nutící čtenáře listovat a hledat v dalších heslech.

  Základní údaje o organizačním vývoji ústředně řízených táborových centrál jsou převzaty ze sborníku GULAG (Glavnoje upravlenije lagerej) 1917-1960, sostavitěli A. I. Kokurin i N. V. Petrov, Rossija XX věk. Dokumenty, Měždunarodnyj fond „Děmokratija), Matěrik, Moskva 2000. Odtud byly čerpány rovněž zeměpisné údaje, které jsou však pro českého čtenáře rozšířeny, údaje o počtech vězňů, které jsou někde doplněny o další informace z jiných zdrojů, a údaje o zaměstnání vězňů, které jsem se však snažil rozvést tak, abych poskytl českému čtenáři přesnější obraz. Do textu je však zpravidla zařazena pouze menší část vnesených nových informací a většinu byla vtělena až do poznámkového aparátu.

  Všechna ostatní hesla jsou výlučně autorská a vznikla na základě studia a sběru materiálů z nejrůznějších tištěných a elektronických podkladů ruské, ukrajinské, polské, slovenské, české, německé a francouzské provenience.

  Zeměpisné pojmy se snaží odpovídat kodifikovaným místním názvům na dobových i současných mapách nebo v geografické literatuře. Bylo ponecháno bez řešení složité a zpravidla téměř nepřeložitelné označování územních jednotek v bývalém Sovětském svazu i v dnešním Rusku a všechny ruské pojmy děrevňa, selo, centralnaja usaďba, posjolok, rabočij posjolok, posjolok rajonnogo podčiněnija, rajonnyj centr, gorod oblastnogo podčiněnija, oblastnyj centr, municipalnoje obrazovanije a mnohé další byly nahrazovány zjednodušeně českými pojmy vesnice, osada, obec, město, okresní město, krajské město a podobně.

  Potíž však představovaly údaje o zeměpisných vzdálenostech. Nelze nepodotknout, že ruské údaje jsou tradičně nepřesné a nejednou téměř tragikomicky rozporuplné. A mapy často mají zkreslený půdorys a pro některé oblasti země ani nejsou veřejně přístupné. Na eventuálních chybných údajích proto nenese autor  vinu a může se pouze omluvit za nesprávné zdroje.

  *Vladimír Bystrov, Praha 2006*

  # Poznámka k elektronickému vydání průvodce

  Přestože uplynulo více než 10 let od doby, kdy Vladimír Bystrov dokončil práci na průvodci, dodnes se jedná v českém prostředí o nepřekonané dílo, které veřejnosti přibližuje rozsah sovětského represivního aparátu. Ústav pro studium totalitních režimů se společně s autorovými pozůstalými rozhodli ponechat původní autorovo dílo ucelené a bez větších zásahů. V době vydání elektronické verze průvodce je ruskou nevládní organizací Memorial budován projekt [Topografie teroru](https://topos.memo.ru/page/text/), která má za cíl mapovat místa spojená s politickými represemi v Sovětském svazu. 

  Mimo to elektronické vydání obsahuje také interaktivní mapu některých táborových správ a samotných táborů, která byla vytvořena na základě databáze [Система исправительно-трудовых лагерей в СССР](http://memo.ru/history/nkvd/gulag) (Sistěma ispravitělno-trudovych lagerej v SSSR) vytvořené z archivních materiálů moskevkou organizací [Memorial](http://memo.ru/). Místa v mapě odkazují na příslušná hesla v průvodci, nejedná se však o jejich přesnou polohu a slouží spíše k snadnější orietaci a zaznačení geogragického rozměru sovětských represí. Jednolivá hesla průvodce jsou přehledně řezena a umožňují vyhledávání na základě svého názvu. Vzhledem k obsáhlosti průvodce nebylo zatím možné vytvořit veškeré přímé reference mezi hesly, proto je možné autorovy odkazy v textu alespoň vyhledat v databázi či manuálně v seznamu hesel.